### ISSUE TITLE
Issues with the flipbook node and tile index

### ISSUE THREAD

**Issue by TheG0oseMan** [DigvijaysinhGohil/Godot-Shader-Lib#4]
Ive downloaded the addon through the Asset Library to animate my particles without using the billboard setting. I use the Godot version 4.1.1 stable. 
Here is my Shader:

![image](https://github.com/DigvijaysinhGohil/Godot-Shader-Lib/assets/160030971/b68615a3-1f2d-47d4-8983-dfd0052a5a8f)

It scales properly and I can adjust the speed for the animation, but the tile order is not what I expect it to be. With the settings shown on the screenshot - flipbook goes in the following order: 1,2,3 7,8,9 4,5,6. 
If I set the start frame as 0 the flipbook will start from 7, if I set it at 1 it will start from 8.

**Comment by DigvijaysinhGohil** [comment]
Issue has been resolved in Shader-Lib version 1.2.2 and version 2.0.2.
