### ISSUE TITLE
[Feature Request] Bump map node 

### ISSUE THREAD

**Issue by emberlightstudios** [DigvijaysinhGohil/Godot-Shader-Lib#5]
Very useful plugin.  Thank you.  I'm surprised a lot of this isn't already available directly in the engine.

Any chance of getting a node to convert grayscale bump baps to normal maps?

This would be useful for procedural normals, e.g. procedural skin shaders.

I am told this is implemented here:
https://www.shadertoy.com/view/Xtd3DS

**Comment by DigvijaysinhGohil** [comment]
I will implement it.

**Comment by emberlightstudios** [comment]
It seems godot handles normal maps a bit differently than most.  I think they do not use the blue channel.  So that example may not work.
