### ISSUE TITLE
Voronoi is not working - Parser Error: Class "VisualShaderNodeProceduralVoronoi" hides a global script class. *solved*

### ISSUE THREAD

**Issue by oidafuxmichi** [DigvijaysinhGohil/Godot-Shader-Lib#8]
I use Voronoi for this caustic-shader.
It works in the editor, but not ingame.

https://gamedevtipsandtricks.blogspot.com/2024/01/fake-caustics-using-visual-shader-in.html

When I use the visual-shader it says:
Parser Error: Class "VisualShaderNodeProceduralVoronoi" hides a global script class.
When I convert visual to script it does not compile.

![image](https://github.com/user-attachments/assets/52fba863-b915-41c4-ac94-0d4cf8ac0079)
![image](https://github.com/user-attachments/assets/1ae1ea36-6c92-4dde-af74-5b74434b6b5f)

I solved this issue by deinstalling shader-lib. You have to delete the shader-lib dir from inside the editor.
then reinstall - will work!

**Comment by DigvijaysinhGohil** [comment]
Seems like when updating, we need to perform a clean install, which is unfortunate. I need to figure something out for it.
